# Arduino program Makefile

# Root path containing the arduino libraries
LIBS_DIR = ..

include $(LIBS_DIR)/config.mk

# SRC =

CXXSRC = /usr/local/src/FastLED/FastLED.cpp

CXXINCS += -I/usr/local/src/FastLED

include $(LIBS_DIR)/tools/rules.mk
