# Arduino program Makefile

# Root path containing the arduino libraries
LIBS_DIR = ..

include $(LIBS_DIR)/config.mk

# SRC =

CXXSRC = ../ardulib/FlexiTimer2.cpp

# CXXINCS =

HAVE_FASTLED = 1
HAVE_PACKETSERIAL = 1

include $(LIBS_DIR)/tools/rules.mk
