# Arduino program Makefile

# Root path containing the arduino libraries 
LIBS_DIR = ..

include $(LIBS_DIR)/config.mk

HAVE_WIRE = 1

# SRC =

CXXSRC = \
	$(LIBS_DIR)/ardulib/Nunchuk.cpp


include $(LIBS_DIR)/tools/rules.mk
