# Arduino program Makefile

# Root path containing the arduino libraries
LIBS_DIR = ..

include $(LIBS_DIR)/config.mk

# SRC =

CXXSRC = \
	$(LIBS_DIR)/ardulib/Pot.cpp

include $(LIBS_DIR)/tools/rules.mk
