# Arduino program Makefile

# Root path containing the arduino libraries 
LIBS_DIR = ..

include $(LIBS_DIR)/config.mk

# SRC =

# CXXSRC = 

HAVE_LIQUID_CRYSTAL = 1

include $(LIBS_DIR)/tools/rules.mk

