# Arduino program Makefile

# Root path containing the arduino libraries 
LIBS_DIR = ..

include $(LIBS_DIR)/config.mk

# SRC = 

CXXSRC = \
	$(LIBS_DIR)/ardulib/ShiftReg.cpp \
	$(LIBS_DIR)/ardulib/Button.cpp \
	Dice.cpp \
	DiceController.cpp


include $(LIBS_DIR)/tools/rules.mk
